class_name GameConstants

const ANIM_IDLE: String = "Idle"
const ANIM_RUN: String = "Run"
const ANIM_JUMP: String = "Jump"
const ANIM_FALL: String = "Fall"
const ANIM_JUMP_PEAK: String = "JumpPeak"
const ANIM_CROUCH: String = "Crouch"
const ANIM_CROUCH_TRANSITION: String = "CrouchTransition"
const ANIM_CROUCH_WALK: String = "CrouchWalk"
const ANIM_ATTACK: String = "Attack"
const ANIM_CROUCH_ATTACK: String = "CrouchAttack"
const ANIM_ROLL: String = "Roll"
const ANIM_DEATH: String = "Death"
const ANIM_TURN_AROUND: String = "TurnAround"
const ANIM_LANDING: String = "Landing"
const ANIM_LANDING_HEAVY: String = "LandingHeavy"
const ANIM_DASH: String = "Dash"
const ANIM_LEDGE_GRAB: String = "LedgeGrab"
const ANIM_LEDGE_CLIMB: String = "LedgeClimb"
const ANIM_WALL_SLIDE: String = "WallSlide"