class_name GameConstants

const ANIM_IDLE = "Idle"
const ANIM_RUN = "Run"
const ANIM_JUMP = "Jump"
const ANIM_FALL = "Fall"
const ANIM_JUMP_PEAK = "JumpPeak"
const ANIM_CROUCH = "Crouch"
const ANIM_CROUCH_TRANSITION = "CrouchTransition"
const ANIM_CROUCH_WALK = "CrouchWalk"
const ANIM_ATTACK = "Attack"
const ANIM_CROUCH_ATTACK = "CrouchAttack"
const ANIM_ROLL = "Roll"
const ANIM_DEATH = "Death"
const ANIM_TURN_AROUND = "TurnAround"
const ANIM_LANDING = "Landing"
const ANIM_LANDING_HEAVY = "LandingHeavy"
const ANIM_DASH = "Dash"
const ANIM_LEDGE_GRAB = "LedgeGrab"
const ANIM_LEDGE_CLIMB = "LedgeClimb"
const ANIM_WALL_SLIDE = "WallSlide"